#!/bin/sh
# Some interfaces such as "chat.z.ai" trim a single long prompt, but accept multiple ".md" attachments

out_path="/scratch"

for f in "dolen_common.c" "dolen_common.h" "dolen_g4u.c" "dolen_g4u_common.c" "dolen_g4u_common.h" "dolen_g4u_quantize.c" "dolen_quantize_common.c" "dolen_quantize_common.h"; do
    out_file_path="${out_path}/${f}.md"
    echo "generating \"${out_file_path}\""
    regarding.py -p "" "$f" > "${out_file_path}"
    done

echo "generating \"${out_path}/dolen.md\""
cat "${out_path}/dolen_"*".md" > "${out_path}/dolen.md"

