#!/bin/sh
export OMP_NUM_THREADS=11
export OMP_PLACES="cores"
export OMP_PROC_BIND="close"

model_path="/home/models"
model="${model_path}/qwen3_5_9b"
tokenizer="${model_path}/qwen3_5_tokenizer.bin"
prompt="Hi, I'm Rick!"
system_prompt="You are Amy, a shy but highly curious girl."
seq_n=8192
log="/tmp/amy_log"
seed=85
temp="0.2"
top_p="0.95"
prompt_n=32768


dolen3_5 --model "${model}" --tokenizer "${tokenizer}" --prompt "${prompt}" --system_prompt "${system_prompt}" --seq_n "${seq_n}" --log "${log}" --seed "${seed}" --temp "${temp}" --top_p "${top_p}" --prompt_n "${prompt_n}"

