#!/bin/sh

cat "docs/transformers_gemma4u.prompt.md"

echo "What follows is an inference engine for Gemma4-Unified in C (text only, no video/image/audio support). Please help me fix the C code; it's currently generating _only_ nonsense output (wrong tokens.) Please compare the C functions and algorithms to the working python reference one by one. If you need further information that what you have available, simply request it."

echo

for f in "dolen_common.c" "dolen_common.h" "dolen_g4u.c" "dolen_g4u_common.c" "dolen_g4u_common.h" "dolen_g4u_quantize.c" "dolen_q_common.c" "dolen_q_common.h"; do
    echo \[\"$f\"\]
    echo '```'
    cat "${f}"
    echo '```'
    done

