#!/bin/sh
export OMP_NUM_THREADS=11
export OMP_PLACES="cores"
export OMP_PROC_BIND="close"

model_type="q3_5"
[ "$1" ] && {
    model_type="$1"
    shift
    }

model_path="/home/models/dolen_models"
model="${model_path}/model_${model_type}"
tokenizer="${model_path}/tokenizer_${model_type}.bin"
system_prompt="You are a helpful assistant."
mode="chat"
seq_n=8192
log="/scratch/dolen_chat.log"
seed=85
temp="0.2"
top_p="0.95"
top_k=40
prompt_n=32768


./"dolen_${model_type}" \
    --model "${model}" \
    --tokenizer "${tokenizer}" \
    --system_prompt "${system_prompt}" \
    --prompt_n "${prompt_n}" \
    --mode "${mode}" \
    --seq_n "${seq_n}" \
    --log "${log}" \
    --seed "${seed}" \
    --temp "${temp}" \
    --top_p "${top_p}" \
    --top_k "${top_k}" \
    "$@"

