#!/bin/sh

prompt="Count from 1 to 10 (e.g., One, Two, ...)."
system_prompt="You are a helpful language model."
seq_n=1024


trap 'echo "CTRL-C pressed"' INT 


for f in "$dolen_model_path/"*".dolq"; do
    $dolen_path/dolen_test_dolq "$f"
    done

