#!/bin/sh

[ "$1" ] || {
    echo "Usage: $0 dolq_path"
    exit -1
    }

model="$1"
prompt="Count from 1 to 10 (e.g., One, Two, ...)."
system_prompt="You are a helpful language model."
seq_n=1024

$dolen_path/dolen \
        --model "$model" \
        --prompt "$prompt" \
        --system_prompt "$system_prompt" \
        --seq_n "$seq_n" \

