#!/bin/sh
. "$dolen_path/envarg.sh"

_bin_name="dolen_chat"
_prefix="${_bin_name}"
_defaults_base="${dolen_path}/${_bin_name}_defaults/${_bin_name}_defaults"
_suffixes="bin model tokenizer system_prompt mode seq_n log seed temp top_p top_k prompt_n threads_n"

envarg_parse "$_bin_name" "$_prefix" "$_defaults_base" "$_suffixes" "$@" &&\
  shift $envarg_parse_shift_count


export OMP_NUM_THREADS="${dolen_chat_threads_n}"
export OMP_PLACES="cores"
export OMP_PROC_BIND="close"


"${dolen_chat_bin}" \
    --model "${dolen_chat_model}" \
    --tokenizer "${dolen_chat_tokenizer}" \
    --system_prompt "${dolen_chat_system_prompt}" \
    --prompt_n "${dolen_chat_prompt_n}" \
    --mode "${dolen_chat_mode}" \
    --seq_n "${dolen_chat_seq_n}" \
    --log "${dolen_chat_log}" \
    --seed "${dolen_chat_seed}" \
    --temp "${dolen_chat_temp}" \
    --top_p "${dolen_chat_top_p}" \
    --top_k "${dolen_chat_top_k}" \
    "$@"

