#!/bin/sh

[ "$1" ] && {
    eg_code="$1"
    }

[ "$eg_code" ] || {
    eg_code="docs/cur_eg.prompt.md"
}

cat "$eg_code"


echo "What follows is an inference engine for Gemma4-Unified in C (text only, no video/image/audio support, no MoE support). Please help me fix the C code; it's currently generating only nonsense output (wrong tokens) - even the first output. Please compare the functions and algorithms to the working llama.cpp reference one by one."

for f in "dolen_common.c" "dolen_common.h" "dolen_g4u.c" "dolen_g4u_common.c" "dolen_g4u_common.h" "dolen_g4u_quantize.c" "dolen_quantize_common.c" "dolen_quantize_common.h"; do
    regarding.py -p "" "$f" 
    done


echo "Here are some configs from the test model:"
cat "docs/gemma-4-12b-it-heretic.config.md"

