#!/bin/sh

[ "$1" ] || {
    echo "Usage: $0 dolq_path"
    exit -1
    }

prompt="The capitol of France is"
seq_n=64

model="$1"
shift

$dolen_path/dolen_run \
        =gen \
        --model "$model" \
        --prompt "$prompt" \
        --seq_n "$seq_n" \
        "$@"

